services:
  frontend:
    build: ./
    container_name: portfolio_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    logging:
      driver: "none"
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
